# /admin/config.yml
backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/uploads"
public_folder: "/assets/uploads"
collections:
  - name: "index"
    label: "Index"
    files:
      - file: "_data/index.yml"
        label: "Homepagina"
        name: "index"
        fields:
          - { label: "Content", name: "content", widget: "markdown" }
