# /admin/config.yml
backend:
  name: git-gateway
  branch: main

locale: nl

media_folder: "src/assets/uploads"
public_folder: "/assets/uploads"
collections:
  - name: "pages"
    label: "Pagina's"
    files:
      - file: "src/_data/index.yml"
        label: "Homepagina"
        name: "index"
        editor:
          preview: false
        fields:
          - { label: "Content1", name: "content1", widget: "markdown" }
          - { label: "Content2", name: "content2", widget: "markdown" }
          - { label: "Content3", name: "content3", widget: "markdown" }
      - file: "src/_data/informatie.yml"
        label: "Informatie"
        name: "informatie"
        editor:
          preview: false
        fields:
          - { label: "Content", name: "content", widget: "markdown" }
  - name: "programma"
    label: "Programma"
    label_singular: "Programma Onderdeel"
    folder: "src/programma"
    editor:
      preview: false
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "markdown" }
      - label: "Artiesten"
        name: "artists"
        widget: "relation"
        collection: "artiesten"
        searchFields: ["name"]
        valueField: "name"
        multiple: true

  - name: "artiesten"
    label: "Artiesten"
    label_singular: "Artiest"
    folder: "src/artiesten"
    editor:
      preview: false
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Bio", name: "bio", widget: "markdown" }
      - { label: "Foto", name: "photo", widget: "image", required: false }
      - {
          label: "Deelnemer Masterclass",
          name: "masterclass_participant",
          widget: "boolean",
          default: false,
        }
