# /admin/config.yml
backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/uploads"
public_folder: "/assets/uploads"
collections:
  - name: "pages"
    label: "Pagina's"
    files:
      - file: "src/_data/index.yml"
        label: "Homepagina"
        name: "index"
        fields:
          - { label: "Content1", name: "content1", widget: "markdown" }
          - { label: "Content2", name: "content2", widget: "markdown" }
          - { label: "Content3", name: "content3", widget: "markdown" }
