# /admin/config.yml
backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/uploads"
public_folder: "/assets/uploads"
collections:
  - name: "pages"
    label: "Pagina's"
    files:
      - file: "src/_data/index.yml"
        label: "Homepagina"
        name: "index"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Content", name: "content", widget: "markdown" }
