# /admin/config.yml
backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/uploads"
public_folder: "/assets/uploads"
collections:
  - name: "pages"
    label: "Pagina's"
    files:
      - file: "src/_data/index.yml"
        label: "Homepagina"
        name: "index"
        editor:
          preview: false
        fields:
          - { label: "Content1", name: "content1", widget: "markdown" }
          - { label: "Content2", name: "content2", widget: "markdown" }
          - { label: "Content3", name: "content3", widget: "markdown" }
      - file: "src/_data/informatie.yml"
        label: "Informatie"
        name: "informatie"
        editor:
          preview: false
        fields:
          - { label: "Content", name: "content", widget: "markdown" }
  - name: "events"
    label: "Events"
    folder: "src/events"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "markdown" }
      - label: "People"
        name: "people"
        widget: "relation"
        collection: "people"
        searchFields: ["name"]
        displayFields: ["name"]
        multiple: true

  - name: "people"
    label: "People"
    folder: "src/people"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Bio", name: "bio", widget: "markdown" }
