# /admin/config.yml
backend:
  name: git-gateway
  branch: main

locale: nl

media_folder: "src/assets/uploads"
public_folder: "/assets/uploads"
collections:
  - name: "pages"
    label: "Pagina's"
    files:
      - file: "src/_data/index.yml"
        label: "Homepagina"
        name: "index"
        editor:
          preview: false
        fields:
          - label: "Carrousel Foto's"
            name: "carrouselImages"
            widget: "list"
            fields:
              - { label: "Foto URL", name: "url", widget: "image" }
          - { label: "Content1", name: "content1", widget: "markdown" }
          - { label: "Content2", name: "content2", widget: "markdown" }
          - {
              label: "Content3",
              name: "content3",
              widget: "markdown",
              required: false,
            }
          - {
              label: "Youtube ID",
              name: "youtubeID",
              widget: "string",
              required: false,
            }
      - file: "src/_data/tickets.yml" # Add this section for the Tickets page
        label: "Tickets"
        name: "tickets"
        editor:
          preview: false
        fields:
          - { label: "Content", name: "content", widget: "markdown" }
      - file: "src/_data/programma.yml" # Add this section for the Tickets page
        label: "Programma"
        name: "programma"
        editor:
          preview: false
        fields:
          - { label: "Content", name: "content", widget: "markdown" }
      - file: "src/_data/informatie.yml"
        label: "Informatie"
        name: "informatie"
        editor:
          preview: false
        fields:
          - { label: "Content", name: "content", widget: "markdown" }
          - label: "Logos"
            name: "logos"
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Alt Text", name: "alt", widget: "string" }
  - name: "programma"
    label: "Programma"
    label_singular: "Programma Onderdeel"
    folder: "src/programma"
    editor:
      preview: false
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Foto", name: "photo", widget: "image" }
      - { label: "Description", name: "Samenvatting", widget: "markdown" }
      - label: "Artiesten"
        name: "artists"
        widget: "relation"
        collection: "artiesten"
        searchFields: ["name"]
        valueField: "name"
        multiple: true
      - { label: "Locatie", name: "location", widget: "string" }
      - { label: "Data en Tijden", name: "datetime", widget: "markdown" }
      - { label: "Meer Informatie", name: "moreinfo", widget: "markdown" }
      - name: "layout"
        widget: "hidden"
        default: "layouts/programma.njk"
      - name: "tags"
        widget: "hidden"
        default: "programmaonderdeel"

  - name: "artiesten"
    label: "Artiesten"
    label_singular: "Artiest"
    folder: "src/artiesten"
    editor:
      preview: false
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Bio", name: "bio", widget: "markdown" }
      - { label: "Foto", name: "photo", widget: "image", required: false }
      - {
          label: "Deelnemer Masterclass",
          name: "masterclass_participant",
          widget: "boolean",
          default: false,
        }
      - name: "tags"
        widget: "hidden"
        default: "artiesten"
